### PR TITLE
Add panic hook so if the app panics the terminal won't become a mess

### PR DESCRIPTION
**Pull request by KarlHeitmann**
Hello,

This is a PR that adds a panic hook, so if the application encounters an unexpected error that will panic. It will not mess up the terminal when abruptly leaving the terminal.

To make the application panic, I just run `cargo run` on this project and scrolled down to the bottom of the git graph, until reaching the first commit and the application panicked with this message:

image

You can see the terminal becomes a mess, and it is difficult to decipher the error message.

With the hook provided in this PR, the application will leave the alternate screen, returning the terminal back to normal, and then will display the panic message.

With the hook, here you can see how the error is displayed when I provoke the same error:

image

I didn't solve the bug, and I don't have a clue what this error is about (which line is failing ????) but at least the error is clear to read and you don't have to reset the terminal :)

Nice project, I started a similar one here: https://github.com/KarlHeitmann/git_explorer , but is still WIP and do not look so nice like yours (also, my graph has some errors). This screenshot is taken from the branch `select_branches`

image

 I'd like to contribute here with some ideas/features. For example, I think it would be so useful to collapse/expand branches with a keystroke so you can hide branches that you are not interested in the moment. But I have not found a tool yet to do that.

I'd also like to group branches that have a similar pattern. For example, all branches that starts with `feature/` are grouped together.

I also put a filter on my project. So you can type "bug" and it will filter all branches that contains the string "bug"

There are many fun things to do with a git graph, I don't know why people just focus on making GUI tools to focus only on working with remote. Also, I'd like to practice my rust skills, I have almost a year studying Rust.

I'll see what else can I do on the "Issues" page. Any feedback on this PR is appreciated.

Best,

### CODE REVIEW

**Comment by mlange-42** [comment]
Hi @KarlHeitmann!

Thank you for this useful contribution!

Generally, further contributions in the directions you point out are highly appreciated.

The patterns feature should already work. For more details, you may want to take a look at https://github.com/mlange-42/git-graph, which is responsible for constructing the graph layout (BTW, the code for this is quite complicated and also a bit messy). You may also want to take a look at the issues there, as this simpler projects seems to be used more than the interative `git-igitt`.

Will test this PR locally as soon as I find the time. Besides that, I am fine to merge it. Will also take a look at your other PR.

**Comment by KarlHeitmann** [comment]
Hi @mlange-42 !

Thanks, your crate [mlange-42/git-graph](https://github.com/mlange-42/git-graph) is nice. I was reading the code and figure out there is a `walk` function on `libgit2`. That's awesome. But I didn't found too messy that repo.

I found this resource: [Learn Rust With Entirely Too Many Linked Lists](https://rust-unofficial.github.io/too-many-lists/#learn-rust-with-entirely-too-many-linked-lists), and I am following the tutorial to learn about `RefCell`, `Rc` and other memory management tools. Once I'll finish I will go to the issues tab of `git-graph`, I didn't take a look at it before, seems very interesting and fun to work on as a side project.

EDIT: As far as what I've seen on your `git-graph` project, I think most of the things I wanted to implement on this repo I could implement them on `git-graph`. Maybe somebody else has a similar idea, can't wait to finish the tutorial to take a look there.

**Comment by mlange-42** [comment]
The project itself is not too messy, it is just the code that does the graph layout that could probably be a bit more structured.

Regarding smart pointer stuff like `RefCell` etc., you will almost never encounter that in my code. So far, I tried to use "default" Rust and stayed away from smart pointers and `unsafe`.

**Comment by KarlHeitmann** [comment]
Nice! I like the philosophy to stay away from complicated things when you can do them the simple way. But sometimes you stumble upon some strange things using another crate and it is useful to know what is goind on. Also you need to practice a lot with both `&` and `&mut` operators to  master them, and that's what I am doing with this `Linked List` tutorial.

Thanks for the encouragement, I hope to see you soon on the projects.

**Pull request merged**
